name: Upload component to https://components.espressif.com

on:
  push:
    branches:
      - esp_based_*

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to the registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "arduino-foc: ."
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
